/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.appsystem.milkteamanage_system.Staff;

import com.appsystem.milkteamanage_system.OrderManage.OrderManage;
import com.appsystem.milkteamanage_system.Utils.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class StaffHomePage extends javax.swing.JFrame {

    private StaffHomePage parent;
    private int staffId;
    private String staffName;
    private String orderType;
    private String orderStatus;
    private double totalAmount;
    private double finalTotalAmount;
    private Map<Integer, JButton> tableButtonMap = new HashMap<>();

    /**
     * Creates new form StaffHomePage
     */
    public StaffHomePage() {
        initComponents();
        //ánh xạ bàn cho map
        initTableButtonMap();
        //check và đổi màu lại cho các Bàn
        checkAndChangeTableButtonBackGround();

    }

    public StaffHomePage(int staffId, String staffName, String orderType) {
        initComponents();
        //ánh xạ bàn cho map
        initTableButtonMap();
        //check và đổi màu lại cho các Bàn
        checkAndChangeTableButtonBackGround();
        this.staffId = staffId;
        this.staffName = staffName;
        this.orderType = orderType;
        staffNameDisplay.setText(staffName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        staffNameDisplay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOrderManage = new javax.swing.JButton();
        btnCreateOrder = new javax.swing.JButton();
        btnlogOut = new javax.swing.JButton();
        btnCreateTogoOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        tableListPanel = new javax.swing.JPanel();
        ban1 = new javax.swing.JButton();
        ban2 = new javax.swing.JButton();
        ban3 = new javax.swing.JButton();
        ban6 = new javax.swing.JButton();
        ban5 = new javax.swing.JButton();
        ban4 = new javax.swing.JButton();
        ban7 = new javax.swing.JButton();
        ban8 = new javax.swing.JButton();
        ban9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideMenu.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("----------------------- Thông Tin Chung -----------------------");

        jLabel2.setText("Nhân Viên: ");

        staffNameDisplay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        staffNameDisplay.setForeground(new java.awt.Color(255, 0, 0));
        staffNameDisplay.setText("Tên Nhân Viên");

        jLabel3.setText("---------------------------- Thao Tác -----------------------------");

        btnOrderManage.setBackground(new java.awt.Color(102, 102, 255));
        btnOrderManage.setText("Quản Lí Hoá Đơn");
        btnOrderManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderManageActionPerformed(evt);
            }
        });

        btnCreateOrder.setBackground(new java.awt.Color(102, 255, 102));
        btnCreateOrder.setText("Tạo  Đơn Tại Quán");
        btnCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrderActionPerformed(evt);
            }
        });

        btnlogOut.setBackground(new java.awt.Color(255, 102, 102));
        btnlogOut.setText("Đăng Xuất");

        btnCreateTogoOrder.setBackground(new java.awt.Color(255, 204, 102));
        btnCreateTogoOrder.setText("Tạo Đơn Mang Đi");
        btnCreateTogoOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTogoOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(staffNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOrderManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(btnCreateTogoOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnlogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(staffNameDisplay))
                .addGap(235, 235, 235)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(btnCreateOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnCreateTogoOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderManage)
                .addGap(43, 43, 43)
                .addComponent(btnlogOut)
                .addGap(44, 44, 44))
        );

        tableListPanel.setBackground(new java.awt.Color(204, 204, 204));

        ban1.setText("Bàn 1");
        ban1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban1ActionPerformed(evt);
            }
        });

        ban2.setText("Bàn 2");
        ban2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban2ActionPerformed(evt);
            }
        });

        ban3.setText("Bàn 3");
        ban3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban3ActionPerformed(evt);
            }
        });

        ban6.setText("Bàn 6");
        ban6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban6ActionPerformed(evt);
            }
        });

        ban5.setText("Bàn 5");
        ban5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban5ActionPerformed(evt);
            }
        });

        ban4.setText("Bàn 4");
        ban4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban4ActionPerformed(evt);
            }
        });

        ban7.setText("Bàn 7");
        ban7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban7ActionPerformed(evt);
            }
        });

        ban8.setText("Bàn 8");
        ban8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban8ActionPerformed(evt);
            }
        });

        ban9.setText("Bàn 9");
        ban9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ban9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tableListPanelLayout = new javax.swing.GroupLayout(tableListPanel);
        tableListPanel.setLayout(tableListPanelLayout);
        tableListPanelLayout.setHorizontalGroup(
            tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableListPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tableListPanelLayout.createSequentialGroup()
                        .addComponent(ban1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(ban2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tableListPanelLayout.createSequentialGroup()
                        .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ban4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ban7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ban5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ban8, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableListPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(ban3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableListPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ban9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ban6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        tableListPanelLayout.setVerticalGroup(
            tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableListPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ban2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ban1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ban3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ban5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ban4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ban6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(tableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ban7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(ban8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ban9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ban1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban1ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(1, tableButtonMap.get(1), staffId, staffName, "Uống tại quán");
    }//GEN-LAST:event_ban1ActionPerformed

    private void ban5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban5ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(5, tableButtonMap.get(5), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban5ActionPerformed

    private void ban4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban4ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(4, tableButtonMap.get(4), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban4ActionPerformed

    private void btnCreateTogoOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTogoOrderActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(0, ban1, staffId, staffName, "Mang đi");
    }//GEN-LAST:event_btnCreateTogoOrderActionPerformed

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void ban2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban2ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(2, tableButtonMap.get(2), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban2ActionPerformed

    private void ban3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban3ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(3, tableButtonMap.get(3), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban3ActionPerformed

    private void ban6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban6ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(6, tableButtonMap.get(6), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban6ActionPerformed

    private void ban7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban7ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(7, tableButtonMap.get(7), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban7ActionPerformed

    private void ban8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban8ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(8, tableButtonMap.get(8), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban8ActionPerformed

    private void ban9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ban9ActionPerformed
        // TODO add your handling code here:
        CheckAndCreateOrder(9, tableButtonMap.get(9), staffId, staffName, "Uống tại quán");

    }//GEN-LAST:event_ban9ActionPerformed

    private void btnOrderManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderManageActionPerformed
        // TODO add your handling code here:
            new OrderManage().setVisible(true);
    }//GEN-LAST:event_btnOrderManageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffHomePage().setVisible(true);
            }
        });
    }

    // ánh xạ và gắn key tương ứng với các bàn
    private void initTableButtonMap() {
        tableButtonMap.put(1, ban1);
        tableButtonMap.put(2, ban2);
        tableButtonMap.put(3, ban3);
        tableButtonMap.put(4, ban4);
        tableButtonMap.put(5, ban5);
        tableButtonMap.put(6, ban6);
        tableButtonMap.put(7, ban7);
        tableButtonMap.put(8, ban8);
        tableButtonMap.put(9, ban9);
    }

    // Kiểm tra các bàn đang có hoá đơn và chuyển màu nút lại.
    private void checkAndChangeTableButtonBackGround() {
        try (Connection conn = DBConnection.getConnection()) {
            String sql = "SELECT TableNumber FROM Orders WHERE OrderType = N'Uống tại quán' AND IsActive = 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int table = rs.getInt("TableNumber");
                JButton btn = tableButtonMap.get(table);
                if (btn != null) {
                    btn.setBackground(new Color(144, 238, 144)); // xanh lá
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tô lại màu bàn: " + e.getMessage());
        }
    }

    //hàm check xem bàn có đang có đơn không để tạo đơn 
    public void CheckAndCreateOrder(int tableNumber, JButton btnBan, int staffId, String staffName, String orderType) {
        try (Connection conn = DBConnection.getConnection()) {
            // Kiểm tra xem bàn này có đơn đang mở không
            String query = "SELECT OrderID,Status,TotalAmount FROM Orders WHERE TableNumber = ? AND OrderType = N'Uống tại quán' AND IsActive = 1";
            PreparedStatement checkPst = conn.prepareStatement(query);
            checkPst.setInt(1, tableNumber);
            ResultSet rs = checkPst.executeQuery();

            if (rs.next()) {
                // check nếu có đơn thì mở ra chi tiết hoá đơn đó
                int existOrderID = rs.getInt("OrderID");
                String orderStatus = rs.getString("Status");
                double totalAmount = rs.getDouble("TotalAmount");
                new OrderFrame(existOrderID, tableNumber, staffId, staffName, orderType, orderStatus, totalAmount, btnBan, this).setVisible(true);
                return;
            }

            // Nếu chưa có thì tạo mới hoá đơn
            String sql = "INSERT INTO Orders (StaffID, TableNumber, OrderType, TotalAmount, IsActive) VALUES (?, ?, ?, 0, 1)";
            PreparedStatement pst = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            pst.setInt(1, staffId);
            if (tableNumber == 0) {
                // Không có bàn
                pst.setNull(2, java.sql.Types.INTEGER);
            } else {
                pst.setInt(2, tableNumber);
            }
            pst.setString(3, orderType);
            pst.executeUpdate();

            ResultSet generatedKeys = pst.getGeneratedKeys();
            if (generatedKeys.next()) {
                int newOrderId = generatedKeys.getInt(1);
                String newOrderStatus = "Chưa thanh toán";
                double newTotalAmount = 0.0;
                btnBan.setBackground(new Color(144, 238, 144)); // Xanh lá nhẹ
                new OrderFrame(newOrderId, tableNumber, staffId, staffName, orderType, newOrderStatus,newTotalAmount, null, this).setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi xử lý bàn: " + e.getMessage());
        }
    }

    //hàm reset màu của Button Bàn tại trang staffhomepage
    public void resetTableButtonColor(int tableNumber) {
        if (tableButtonMap.containsKey(tableNumber)) {
            tableButtonMap.get(tableNumber).setBackground(null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ban1;
    private javax.swing.JButton ban2;
    private javax.swing.JButton ban3;
    private javax.swing.JButton ban4;
    private javax.swing.JButton ban5;
    private javax.swing.JButton ban6;
    private javax.swing.JButton ban7;
    private javax.swing.JButton ban8;
    private javax.swing.JButton ban9;
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnCreateTogoOrder;
    private javax.swing.JButton btnOrderManage;
    private javax.swing.JButton btnlogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JLabel staffNameDisplay;
    private javax.swing.JPanel tableListPanel;
    // End of variables declaration//GEN-END:variables
}
